SYSTEM_DISPOSITION_MAPPING = {
    1: "Positive w/Amount",
    2: "Positive no Amount",
    3: "Negative — DNC — Skill",
    4: "Negative — DNC — BU",
    5: "Negative",
    6: "Other",
    7: "Retry — Rescheduled Agent Specific",
    8: "Retry — Rescheduled Specified Date/Time — Any Agent",
    9: "Retry — Rescheduled Later Date/Time Unspecified",
    10: "Retry — Not Available",
    11: "Retry — Answering Machine",
    12: "Final — Answering Machine",
    13: "Fax Machine",
    14: "Answering Machine Left Message",
    15: "Busy",
    16: "Error",
    17: "Fax",
    18: "Invalid Number",
    19: "Answering Machine",
    20: "No Answer",
    21: "Number Changed",
    22: "Disconnect",
    23: "Network Busy",
    24: "Abandon",
    25: "Agent Abandon",
    26: "Manual Suppression",
    27: "Webservice Suppression",
    28: "IVR Suppression",
    29: "Script Action Suppression",
    30: "Bulk Upload Suppression",
    31: "None",
    32: "Called Party Hang Up",
    33: "Force Agent Disconnect",
    34: "Call Takeover",
    35: "Disposition Timeout",
    36: "No Disposition",
    37: "Forced Remove Call",
    38: "System Failure",
    39: "No Ports",
    40: "Bad Number",
    41: "Retry - Preview Requeue",
    42: "Third Party — Cell Phone",
    43: "Third Party — DNC",
    44: "Third Party — Time Zone Restricted",
    45: "Third Party — Legislative Restricted",
    46: "Script Action 1",
    47: "Script Action 2",
    48: "No Scripting Disposition",
    49: "Agent Specific — Queue Is Full Final",
    50: "Agent Specific — Queue Is Full",
    51: "Callback Undeliverable",
    52: "Agent Specific — Agent Unavailable Final",
    53: "Agent Specific — Agent Unavailable",
    54: "Agent Specific — Agentless Skill Final",
    55: "ISDN Cause Code 18",
    56: "ISDN Cause Code 21",
    57: "ISDN Cause Code 102",
    58: "SysUnclassified",
    60: "DialerBlendingRetry",
    61: "Reactivation",
    62: "SMS Final - Destination",
    63: "SMS Transport Failure Retry",
    64: "SMS Failure",
    65: "SMS Failure Message too Long",
    66: "SMS Failure Invalid Transport Code",
    67: "Email Final",
    68: "Email Failure",
    69: "Email Retry",
    70: "SMS Final - Record",
    71: "SMS Retry",
    72: "Retry - Snooze",
    73: "Retry Preview Rescheduled Agent Specific",
    74: "Retry Preview Rescheduled Any Agent",
    75: "Preview Reject - Positive",
    76: "Preview Reject - Positive w/Amount",
    77: "Preview Reject - Negative",
    78: "Preview Reject - Negative DNC BU",
    79: "Preview Reject - Negative DNC Skill",
    80: "Preview Reject - Negative Other",
    81: "Proactive Identified - Fax",
    82: "Proactive Identified - Answering Machine",
    83: "Proactive Identified - Bad Number",
    84: "Proactive Identified - Answering Machine Left Message Long",
    85: "Agent Session Timed Out",
    86: "Agent Override Answering Machine - No Message",
    87: "Agent Override Answering Machine - System Left Message",
    90: "Call Blocked by Carrier Analytics",
    91: "Call Refused By Customer",
    92: "Live Person Left Message",
    93: "Live Person Left Message Attempts Max",
    94: "Live Person Left Message Partial",
    95: "Answering Machine Left Message Partial",
    96: "Answering Machine Left Message Attempts Max",
    97: "Agent Override Fax Machine",
    98: "Invalid Caller ID",
}


CONTACT_HISTORY_FIELDS = [
    "abandoned",
    "agentId",
    "firstName",
    "lastName",
    "masterContactId",
    "contactStartDate",
    "skillId",
    "skillName",
    "isOutbound",
    "primaryDispositionId",
    "contactId",
]

SYSTEM_DISPOSITION_CATEGORY_MAPPING = {
    # Voicemail / Answering Machine
    "Agent Override Answering Machine - No Message": "Voicemail / Answering Machine",
    "Agent Override Answering Machine - System Left Message": "Voicemail / Answering Machine",
    "Answering Machine": "Voicemail / Answering Machine",
    "Answering Machine Left Message": "Voicemail / Answering Machine",
    "Answering Machine Left Message Attempts Max": "Voicemail / Answering Machine",
    "Answering Machine Left Message Partial": "Voicemail / Answering Machine",
    "Live Person Left Message": "Voicemail / Answering Machine",
    "Live Person Left Message Attempts Max": "Voicemail / Answering Machine",
    "Live Person Left Message Partial": "Voicemail / Answering Machine",
    "Retry — Answering Machine": "Voicemail / Answering Machine",
    "Final — Answering Machine": "Voicemail / Answering Machine",
    "Proactive Identified - Answering Machine": "Voicemail / Answering Machine",
    "Proactive Identified - Answering Machine Left Message Long": "Voicemail / Answering Machine",
    # Interrupted Call
    "Called Party Hang Up": "Interrupted Call",
    "Force Agent Disconnect": "Interrupted Call",
    # Fax Machine
    "Fax Machine": "Fax Machine",
    "Fax": "Fax Machine",
    "Proactive Identified - Fax": "Fax Machine",
    "Agent Override Fax Machine": "Fax Machine",
    # Error / Failure
    "Error": "Error / Failure",
    "Number Changed": "Error / Failure",
    "Disconnect": "Error / Failure",
    "Network Busy": "Error / Failure",
    "Call Takeover": "Error / Failure",
    "Disposition Timeout": "Error / Failure",
    "No Disposition": "Error / Failure",
    "Forced Remove Call": "Error / Failure",
    "System Failure": "Error / Failure",
    "No Ports": "Error / Failure",
    "Bad Number": "Error / Failure",
    "ISDN Cause Code 18": "Error / Failure",
    "ISDN Cause Code 21": "Error / Failure",
    "ISDN Cause Code 102": "Error / Failure",
    "SysUnclassified": "Error / Failure",
    "SMS Failure": "Error / Failure",
    "SMS Failure Message too Long": "Error / Failure",
    "SMS Failure Invalid Transport Code": "Error / Failure",
    "Email Failure": "Error / Failure",
    "SMS Final - Record": "Error / Failure",
    "Agent Session Timed Out": "Error / Failure",
    "Invalid Caller ID": "Error / Failure",
    "Proactive Identified - Bad Number": "Error / Failure",
    # Supressed
    "Manual Suppression": "Suppressed",
    "Webservice Suppression": "Suppressed",
    "IVR Suppression": "Suppressed",
    "Script Action Suppression": "Suppressed",
    "Bulk Upload Suppression": "Suppressed",
    "Script Action 1": "Suppressed",
    "Script Action 2": "Suppressed",
}

ANSWERED_DISPOSITIONS = [
    "Audio/Connectivity Issues",
    "Call Back (Outbound)",
    "Completed",
    "Deceased",  # cannot convert
    "Declined",
    "Do Not Call",
    "Ineligible-Hospice",  # cannot convert
    "Ineligible-LTC",  # cannot convert
    "Member Authenticated",
    "Opted Out",
    "Other-Unable to Complete",
    "Pharmacy Call-Complete",
    "Previously Completed",  # cannot convert
    "Service Offered",
    "Transferred to agent",  # cannot convert, but when calculating agent specific conversion rate,
    # this needs to be treated as a conversion for some skills
    "Transferred to 3rd party",  # cannot convert
    "Unavailable",
    "Wrong Number",  # cannot convert
]

CONVERTABLE_DISPOSITIONS = [
    "Audio/Connectivity Issues",
    "Call Back (Outbound)",
    "Completed",
    "Declined",
    "Do Not Call",
    "Member Authenticated",
    "Opted Out",
    "Other-Unable to Complete",
    "Pharmacy Call-Complete",
    "Service Offered",
    "Unavailable",
]

CONVERTED_DISPOSITIONS = [
    "Completed",
    "Pharmacy Call-Complete",
    # add one for fax verification completion
]

PHARMACIST_TEAMS = ["Pharmacist", "Contractor-RPH", "New Hire-RPH", "Intern"]
PHARMACY_ASSOCIATE_TEAMS = ["Pharmacy Associate", "NH-Clerk"]
IGNORED_TEAMS = [
    "Admin Team",
    "Operations",
    "InfoSys",
    "CMAPP Data Team",
    "Program Leads",
]

PRIORITY_PHARMACIST_SKILLS = {
    "23053343": "CMR-Humana-Shout-OB",
    "23053505": "CMR-Humana-Shout-SPA-OB",
    "29265705": "Adherence-Aetna-MAPD-OB",
    "23053352": "Adherence-Aetna-PDP-OB",
    "23053483": "COA-Humana-OB",
}

PRIORITY_PHARMACY_ASSOCIATE_SKILLS = {
    "23053477": "Adherence-MBR-ELV-OB",
    "23122240": "Adherence-Pharmacy-OB",
    "23053353": "DSC-Humana-OB",
    "23053484": "Refill-DSC-MercyCare-OB",
    "29265711": "SUPDSPC-AET-PDP-OB",
}

PDP_CONTRACTS = ["S5601"]

DISPO_MAPPING = {
    "Positive w/Amount": "UNKNOWN",
    "Positive no Amount": "UNKNOWN",
    "Negative — DNC — Skill": "DNC",
    "Negative — DNC — BU": "DNC",
    "Negative": "UNKNOWN",
    "Other": "Invalid Number",
    "Retry — Rescheduled Agent Specific": "Other-Unable to Complete",
    "Retry — Rescheduled Specified Date/Time — Any Agent": "Other-Unable to Complete",
    "Retry — Rescheduled Later Date/Time Unspecified": "Other-Unable to Complete",
    "Retry — Not Available": "Member Unavailable",
    "Retry — Answering Machine": "Left VM",
    "Final — Answering Machine": "Left VM",
    "Fax Machine": "Invalid Number",
    "Answering Machine Left Message": "Left VM",
    "Busy": "No Answer",
    "Error": "Audio/Connectivity Issues",
    "Fax": "Invalid Number",
    "Invalid Number": "Invalid Number",
    "Answering Machine": "Left VM",
    "No Answer AM": "No Answer",
    "No Answer / Answering Machine": "No Answer",
    "Number Changed": "Wrong Number",
    "Disconnect": "Invalid Number",
    "Network Busy": "No Answer",
    "Abandon": "Audio/Connectivity Issues",
    "Agent Abandon": "Audio/Connectivity Issues",
    "Manual Suppression": "DNC",
    "Webservice Suppression": "UNKNOWN",
    "IVR Suppression": "UNKNOWN",
    "Script Action Suppression": "REMOVE",
    "Bulk Upload Suppression": "UNKNOWN",
    "None": "Other-Unable to Complete",
    "Called Party Hang Up": "Audio/Connectivity Issues",
    "Force Agent Disconnect": "Audio/Connectivity Issues",
    "Call Takeover": "Other-Unable to Complete",
    "Disposition Timeout": "Other-Unable to Complete",
    "No Disposition": "Other-Unable to Complete",
    "Forced Remove Call": "Other-Unable to Complete",
    "System Failure": "Audio/Connectivity Issues",
    "No Ports": "Audio/Connectivity Issues",
    "Bad Number": "Invalid Number",
    "Retry - Preview Requeue": "Other-Unable to Complete",
    "Third Party — Cell Phone": "Other-Unable to Complete",
    "Third Party — DNC": "DNC",
    "Third Party — Time Zone Restricted": "Other-Unable to Complete",
    "Third Party — Legislative Restricted": "Other-Unable to Complete",
    "Script Action 1": "REMOVE",
    "Script Action 2": "REMOVE",
    "No Scripting Disposition": "UNKNOWN",
    "Agent Specific — Queue Is Full Final": "UNKNOWN",
    "Agent Specific — Queue Is Full": "UNKNOWN",
    "Callback Undeliverable": "Audio/Connectivity Issues",
    "Agent Specific — Agent Unavailable Final": "Audio/Connectivity Issues",
    "Agent Specific — Agent Unavailable": "Audio/Connectivity Issues",
    "Agent Specific — Agentless Skill Final": "Audio/Connectivity Issues",
    "ISDN Cause Code 18": "Audio/Connectivity Issues",
    "ISDN Cause Code 21": "Audio/Connectivity Issues",
    "ISDN Cause Code 102": "Audio/Connectivity Issues",
    "SysUnclassified": "UNKNOWN",
    "DialerBlendingRetry": "UNKNOWN",
    "Reactivation": "UNKNOWN",
    "SMS Final - Destination": "REMOVE",
    "SMS Transport Failure Retry": "REMOVE",
    "SMS Failure": "REMOVE",
    "SMS Failure Message too Long": "REMOVE",
    "SMS Failure Invalid Transport Code": "REMOVE",
    "Email Final": "REMOVE",
    "Email Failure": "REMOVE",
    "Email Retry": "REMOVE",
    "SMS Final - Record": "REMOVE",
    "SMS Retry": "REMOVE",
    "Retry - Snooze": "Audio/Connectivity Issues",
    "Retry - Preview Rescheduled Agent Specific": "Audio/Connectivity Issues",
    "Retry - Preview Rescheduled Any Agent": "Audio/Connectivity Issues",
    "Preview Reject - Positive": "Audio/Connectivity Issues",
    "Preview Reject - Positive w/Amount": "Audio/Connectivity Issues",
    "Preview Reject - Negative": "Audio/Connectivity Issues",
    "Preview Reject - Negative DNC BU": "DNC",
    "Preview Reject - Negative DNC Skill": "DNC",
    "Preview Reject - Negative Other": "Other-Unable to Complete",
    "Proactive Identified - Fax": "Invalid Number",
    "Proactive Identified - Answering Machine": "Left VM",
    "Proactive Identified - Bad Number": "Invalid Number",
    "Proactive Identified - Answering Machine Left Message Long": "Left VM",
    "Agent Session Timed Out": "Audio/Connectivity Issues",
    "Agent Override Answering Machine - No Message": "Left VM",
    "Agent Override Answering Machine - System Left Message": "Left VM",
    "Call Blocked by Carrier Analytics": "Audio/Connectivity Issues",
    "Call Refused By Customer": "No Answer",
    "Live Person Left Message": "Left VM",
    "Live Person Left Message Attempts Max": "Left VM",
    "Live Person Left Message Partial": "Left VM",
    "Answering Machine Left Message Partial": "Left VM",
    "Answering Machine Left Message Attempts Max": "Left VM",
    "Agent Override Fax Machine": "Invalid Number",
    "Agent Override Fax machine": "Invalid Number",
    "Audio/Connectivity Issues": "Audio/Connectivity Issues",
    "Call Back (Outbound)": "Member Unavailable",
    "Call Queued For later": "Audio/Connectivity Issues",
    # Dont Drop Completed
    "Completed": "Completed",
    "Deceased": "Use CMAPP Data / REMOVE",
    "Declined": "Declined",
    "Do Not Call": "DNC",
    "Ineligible-LTC": "LTC",
    "Ineligible-Hospice": "Hospice",
    "Left Voicemail": "Left VM",
    "Member Authenticated": "Member Authenticated",
    "No Answer": "No Answer",
    "Opted Out": "Use CMAPP Data / REMOVE",
    "Other-Unable to Complete": "Other-Unable to Complete",
    "Pharmacy Call-Complete": "REMOVE",
    "Previously Completed": "REMOVE",
    "Robo Response": "Other-Unable to Complete",
    "Service Offered": "Service Offered, Deferred",
    "Unavailable": "Member Unavailable",
    "Wrong Number": "Wrong Number",
    "Left Recorded Message": "Left VM",
    "UNKNOWN": "REMOVE",
    "Transferred to agent": "Transferred",
    "Transferred to Agent": "Transferred",
    "Automatic Transfer": "REMOVE",
}

PRESENTATION_MAPPING = {
    "Audio/Connectivity Issues": "Left VM/Member Unavailable",
    "Completed": "Completed",
    "Deceased": "Deceased",
    "Declined": "Declined",
    "DNC": "DNC",
    "Invalid Number": "Invalid Number",
    "Left VM": "Left VM/Member Unavailable",
    "Member Unavailable": "Left VM/Member Unavailable",
    "No Answer": "Left VM/Member Unavailable",
    "Other-Unable to Complete": "Left VM/Member Unavailable",
    "Service Offered, Deferred": "Service Offered, Deferred",
    "Transferred": "Transferred",
    "Wrong Number": "Invalid Number",
}


VALID_AREA_CODES = [
    "205","251","256","334","659","938",
    "907",
    "480","520","602","623","928",
    "327","479","501","870",
    "209","213","279","310","323","341","350","369","408","415","424","442","510","530","559",
    "562","619","626","628","650","657","661","669","707","714","747","760","805","818","820",
    "831","840","858","909","916","925","949","951",
    "303","719","720","970","983",
    "203","475","860","959",
    "302",
    "239","305","321","324","352","386","407","448","561","645","656","689","727","728","754",
    "772","786","813","850","863","904","941","954",
    "229","404","470","478","678","706","762","770","912","943",
    "808",
    "208","986",
    "217","224","309","312","331","447","464","618","630","708","730","773","779","815","847",
    "861","872",
    "219","260","317","463","574","765","812","930",
    "319","515","563","641","712",
    "316","620","785","913",
    "270","364","502","606","859",
    "225","318","337","504","985",
    "207",
    "227","240","301","410","443","667",
    "339","351","413","508","617","774","781","857","978",
    "231","248","269","313","517","586","616","734","810","906","947","989",
    "218","320","507","612","651","763","952",
    "228","601","662","769",
    "235","314","417","557","573","636","660","816","975",
    "406",
    "308","402","531",
    "702","725","775",
    "603",
    "201","551","609","640","732","848","856","862","908","973",
    "505","575",
    "212","315","329","332","347","363","516","518","585","607","624","631","646","680","716",
    "718","838","845","914","917","929","934",
    "252","336","472","704","743","828","910","919","980","984",
    "701",
    "216","220","234","283","326","330","380","419","436","440","513","567","614","740","937",
    "405","539","572","580","918",
    "458","503","541","971",
    "215","223","267","272","412","445","484","570","582","610","717","724","814","835","878",
    "401",
    "803","839","843","854","864",
    "605",
    "423","615","629","731","865","901","931",
    "210","214","254","281","325","346","361","409","430","432","469","512","682","713","726",
    "737","806","817","830","832","903","915","936","940","945","956","972","979",
    "385","435","801",
    "802",
    "276","434","540","571","686","703","757","804","826","948",
    "206","253","360","425","509","564",
    "202","771",
    "304","681",
    "262","274","353","414","534","608","715","920",
    "307",
]

PACIFIC_AREA_CODES = [
    "209","213","279","310","323","341","350","369","408","415","424","442","510",
    "530","559","562","619","626","628","650","657","661","669","707","714","747",
    "760","805","818","820","831","840","858","909","916","925","949","951",
    "206","253","360","425","509","564",
    "458","503","541","971",
    "702","725","775"
]